[tool.poetry]
name = "meine-stadt-transparent"
version = "0.2.0"
description = "A website to bring municipal politics to citizens"
authors = ["Tobias Hößl <tobias@hoessl.eu>", "Konstantin Schütze <konstin@mailbox.org>"]
license = "MIT"

[tool.poetry.dependencies]
Django = "~2.2"
django-allauth = "^0.39"
django-anymail = "^6.0"
django-braces = "^1.13"
django_csp = "^3.4"
django-elasticsearch-dsl = "^0.5"
django-environ = "^0.4"
django-geojson = "^2.12"
django-settings-export = "^1.2"
django-simple-history = "^2.3"
django-webpack-loader = "^0.6"
django-widget-tweaks = "^1.4"
elasticsearch-dsl = "^5.4"
geoextract = "^0.3.1"
geopy = "^1.18"
gunicorn = "^19.9"
html2text = "^2018.1"
icalendar = "^4.0"
jsonfield = "^2.0"
mysqlclient = "^1.3"
pgpy = { version = "^0.4.3", optional = true }
PyPDF2 = "^1.26"
python = "^3.5"
python-slugify = "^2.0"
requests = "^2.19"
splinter = "^0.10"
Wand = "^0.5.0"
sentry-sdk = "^0.7.2"
minio = "^4.0"
tqdm = "^4.29"
python-dateutil = "^2.7"
wagtail = { git = "https://github.com/wagtail/wagtail", branch = "master" }
django-decorator-include = "^2.1"


[tool.poetry.dev-dependencies]
selenium = "3.141.0"
tox = "^3.7"
django-debug-toolbar = "^1.11"
# We can't directly depend on black here because then we'd need to require python 3.6 as minimum

[tool.poetry.extras]
pgp = ["pgpy"]

[build-system]
requires = ["poetry >= 0.12, <1"]
build-backend = "poetry.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.tox
  | mainapp/migrations
  | cms/migrations
  | importer/migrations
  | node_modules
  | static
)/
'''
